version: '25.0.3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=librarysystem
      - DB_USERNAME=root
      - DB_PASSWORD=root
      # Add other environment variables as needed

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=librarysystem
      # Add other MySQL environment variables as needed

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql