version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      # Add other environment variables as needed

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=librarysystem
      # Add other MySQL environment variables as needed
